src/Cydream/PlatformBundle/Entity/Image.php
<?php

namespace Cydream\PlatformBundle\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\HttpFoundation\File\UploadedFile;

/**
 * Image
 *
 * @ORM\Table(name="image")
 * @ORM\Entity(repositoryClass="Cydream\PlatformBundle\Repository\ImageRepository")
 */
class Image
{
    private $file;
    
    public function getFile()
    {
      return $this->file;
    }
  
    public function setFile(UploadedFile $file = null)
    {
      $this->file = $file;
    }

    public function upload()
    {
      // Si jamais il n'y a pas de fichier (champ facultatif), on ne fait rien
      if (null === $this->file) {
        return;
      }
  
      // On récupère le nom original du fichier de l'internaute
      $name = $this->file->getClientOriginalName();
  
      // On déplace le fichier envoyé dans le répertoire de notre choix
      $this->file->move($this->getUploadRootDir(), $name);
  
      // On sauvegarde le nom de fichier dans notre attribut $url
      $this->url = $name;
  
      // On crée également le futur attribut alt de notre balise <img>
      $this->alt = $name;
    }
  
    public function getUploadDir()
    {
      // On retourne le chemin relatif vers l'image pour un navigateur (relatif au répertoire /web donc)
      return 'uploads/img';
    }
  
    protected function getUploadRootDir()
    {
      // On retourne le chemin relatif vers l'image pour notre code PHP
      return __DIR__.'/../../../../web/'.$this->getUploadDir();
    }

    /**
     * @var int
     *
     * @ORM\Column(name="id", type="integer")
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     */
    private $id;

    /**
     * @var string
     *
     * @ORM\Column(name="url", type="string", length=255)
     */
    private $url;

    /**
     * @var string
     *
     * @ORM\Column(name="alt", type="string", length=255)
     */
    private $alt;


    /**
     * Get id
     *
     * @return int
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set url
     *
     * @param string $url
     *
     * @return Image
     */
    public function setUrl($url)
    {
        $this->url = $url;

        return $this;
    }

    /**
     * Get url
     *
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Set alt
     *
     * @param string $alt
     *
     * @return Image
     */
    public function setAlt($alt)
    {
        $this->alt = $alt;

        return $this;
    }

    /**
     * Get alt
     *
     * @return string
     */
    public function getAlt()
    {
        return $this->alt;
    }
}

src/Cydream/PlatformBundle/Form/AdvertType.php
<?php

namespace Cydream\PlatformBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

use Symfony\Component\Form\Extension\Core\Type\CheckboxType;
use Symfony\Component\Form\Extension\Core\Type\DateType;
use Symfony\Component\Form\Extension\Core\Type\FormType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextareaType;
use Symfony\Component\Form\Extension\Core\Type\TextType;

use Symfony\Bridge\Doctrine\Form\Type\EntityType;


class AdvertType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
        ->add('date',DateType::class)
        ->add('title',TextType::class)
        ->add('content',TextareaType::class)
        ->add('author',TextType::class)
        ->add('published',CheckboxType::class, array('required' => false))
        ->add('image',     ImageType::class)
        ->add('categories', EntityType::class, array(
            'class'   => 'CydreamPlatformBundle:Category',
            'choice_label' => 'name',
            'multiple'     => true,
        
          ))
       ->add('save',SubmitType::class);
    }
    
    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'Cydream\PlatformBundle\Entity\Advert'
        ));
    }

    /**
     * {@inheritdoc}
     */
    public function getBlockPrefix()
    {
        return 'cydream_platformbundle_advert';
    }


}

src/Cydream/PlatformBundle/Controller/AdvertController.php
<?php

namespace Cydream\PlatformBundle\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\HttpFoundation\Request;

use Cydream\PlatformBundle\Entity\Advert;
use Cydream\PlatformBundle\Entity\Image;
use Cydream\PlatformBundle\Entity\Application;
use Cydream\PlatformBundle\Form\AdvertType;
use Cydream\PlatformBundle\Form\AdvertEditType;


class AdvertController extends Controller
{
    public function indexAction($page)
    {
        $nbPerPage =    3;

        if ($page < 1) {
            throw new NotFoundHttpException("Page '$page' inexistante.");
        }
        $em = $this->getDoctrine()->getManager();
        $adverts= $em->getRepository('CydreamPlatformBundle:Advert')->getAdverts($page,$nbPerPage);

        // On calcule le nombre total de pages grâce au count($listAdverts) qui retourne le nombre total d'annonces
        $nbPages = ceil(count($adverts) / $nbPerPage);

        if ($page > $nbPages) {
            throw new NotFoundHttpException("Page '$page' inexistante.");
        }
        return $this->render('CydreamPlatformBundle:Advert:index.html.twig',[
            'listAdverts'=>$adverts,
            'page'=>$page,
            'nbPages'=>$nbPages,
        ]);
    }

    public function viewAction($id)
    {

        $em = $this->getDoctrine()
            ->getManager();

        // On récupère le repository
        $repository = $em->getRepository('CydreamPlatformBundle:Advert');

        // On récupère l'entité correspondante à l'id $id
        $advert = $repository->find($id);

        // $advert est donc une instance de Cydream\PlatformBundle\Entity\Advert
        // ou null si l'id $id  n'existe pas, d'où ce if :
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }

        $applications = $em->getRepository('CydreamPlatformBundle:Application')->findBy(['advert'=>$advert]);

        $advertSkills = $em->getRepository('CydreamPlatformBundle:AdvertSkill')->findBy(['advert'=>$advert]);

        // Le render ne change pas, on passait avant un tableau, maintenant un objet
        return $this->render('CydreamPlatformBundle:Advert:view.html.twig', array(
            'advert' => $advert,
            "applications" => $applications,
            'listAdvertSkills' => $advertSkills,
        ));


    }

    public function addAction(Request $request)
    {
        // Création de l'entité
        $advert = new Advert();

        $form = $this->createForm(AdvertType::class, $advert);
        /*
        $formBuilder=$this->get('form.factory')->createBuilder(FormType::class,$advert);

        $formBuilder
            ->add('date',DateType::class)
            ->add('title',TextType::class)
            ->add('content',TextareaType::class)
            ->add('author',TextType::class)
            ->add('published',CheckboxType::class, array('required' => false))
            ->add('save',SubmitType::class);

         $form = $formBuilder->getForm();
        */
        // Si la requête est en POST
        if ($request->isMethod('POST')) {
            // On fait le lien Requête <-> Formulaire
            // À partir de maintenant, la variable $advert contient les valeurs entrées dans le formulaire par le visiteur
            $form->handleRequest($request);

            // On vérifie que les valeurs entrées sont correctes
            // (Nous verrons la validation des objets en détail dans le prochain chapitre)
            if ($form->isValid()) {

                // Ajoutez cette ligne :
                // c'est elle qui déplace l'image là où on veut les stocker
                $advert->getImage()->upload();
      
                // On enregistre notre objet $advert dans la base de données, par exemple
                $em = $this->getDoctrine()->getManager();
                $em->persist($advert);
                $em->flush();

                
                $request->getSession()->getFlashBag()->add('notice', 'Annonce bien enregistrée.');

                // On redirige vers la page de visualisation de l'annonce nouvellement créée
                return $this->redirectToRoute('oc_platform_view', array('id' => $advert->getId()));
            }
        }

        // À ce stade, le formulaire n'est pas valide car :
        // - Soit la requête est de type GET, donc le visiteur vient d'arriver sur la page et veut voir le formulaire
        // - Soit la requête est de type POST, mais le formulaire contient des valeurs invalides, donc on l'affiche de nouveau
        return $this->render('CydreamPlatformBundle:Advert:add.html.twig', array(
        'form' => $form->createView(),
        ));
    }

    public function editAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        
        // On récupère l'annonce $id
        $advert = $em->getRepository('CydreamPlatformBundle:Advert')->find($id);
    
        if (null === $advert) {
            throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
        }
    
        $form = $this->createForm(AdvertEditType::class, $advert);        

    
        // Pour persister le changement dans la relation, il faut persister l'entité propriétaire
        // Ici, Advert est le propriétaire, donc inutile de la persister car on l'a récupérée depuis Doctrine
    
        // Étape 2 : On déclenche l'enregistrement
        $em->flush();

        if ($request->isMethod('POST')) {
            $form->handleRequest($request);
            if ($form->isValid()) {
                $request->getSession()->getFlashBag()->add('notice', 'Annonce bien modifiée');
                return $this->redirectToRoute('oc_platform_view', ['id' => 5]);
            }
        }
        return $this->render('CydreamPlatformBundle:Advert:edit.html.twig',[
            'form'=>$form->createView(),
            'advert'=>$form->createView(),
        ]); 
    }

    public function deleteAction($id, Request $request)
    {
        $em = $this->getDoctrine()->getManager();
        
            $advert = $em->getRepository('CydreamPlatformBundle:Advert')->find($id);
        
            if (null === $advert) {
              throw new NotFoundHttpException("L'annonce d'id ".$id." n'existe pas.");
            }
        
            // On crée un formulaire vide, qui ne contiendra que le champ CSRF
            // Cela permet de protéger la suppression d'annonce contre cette faille
            $form = $this->get('form.factory')->create();
        
            if ($request->isMethod('POST') && $form->handleRequest($request)->isValid()) {
              $em->remove($advert);
              $em->flush();
        
              $request->getSession()->getFlashBag()->add('info', "L'annonce a bien été supprimée.");
        
              return $this->redirectToRoute('oc_platform_home');
            }
            
            return $this->render('CydreamPlatformBundle:Advert:delete.html.twig', array(
              'advert' => $advert,
              'form'   => $form->createView(),
            ));    }
}

src/Cydream/PlatformBundle/Resources/views/Advert/add.html.twig
{% extends "CydreamPlatformBundle::layout.html.twig" %}

{% block body %}

  <h2>Ajouter une annonce</h2>

  {{ include("CydreamPlatformBundle:Advert:form.html.twig") }}

  <p>
    Attention : cette annonce sera ajoutée directement
    sur la page d'accueil après validation du formulaire.
  </p>

{% endblock %}

src/Cydream/PlatformBundle/Resources/views/Advert/delete.html.twig
{# src/Cydream/PlatformBundle/Resources/views/Advert/delete.html.twig #}

{% extends "CydreamPlatformBundle::layout.html.twig" %}

{% block title %}
  Supprimer une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Supprimer une annonce</h2>

  <p>
    Etes-vous certain de vouloir supprimer l'annonce "{{ advert.title }}" ?
  </p>

  {# On met l'id de l'annonce dans la route de l'action du formulaire #}
  <form action="{{ path('oc_platform_delete', {'id': advert.id}) }}" method="post">
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
    {# Ici j'ai écrit le bouton de soumission à la main #}
    <input type="submit" value="Supprimer" class="btn btn-danger" />
    {# Ceci va générer le champ CSRF #}
    {{ form_rest(form) }}
  </form>

{% endblock %}

src/Cydream/PlatformBundle/Resources/views/Advert/edit.html.twig
{% extends "CydreamPlatformBundle::layout.html.twig" %}

{% block title %}
  Modifier une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Modifier une annonce</h2>

  {{ include("CydreamPlatformBundle:Advert:form.html.twig") }}

  <p>
    Vous éditez une annonce déjà existante, merci de ne pas changer
    l'esprit générale de l'annonce déjà publiée.
  </p>

  <p>
    <a href="{{ path('oc_platform_view', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à l'annonce
    </a>
  </p>

{% endblock %}

src/Cydream/PlatformBundle/Resources/views/Advert/form.html.twig
<h3>Formulaire d'annonce</h3>

<div class="well">
  {{ form(form) }}
</div>

src/Cydream/PlatformBundle/Resources/views/Advert/index.html.twig
{% extends "CydreamPlatformBundle::layout.html.twig" %}

{% block title %}
  Accueil - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <h2>Liste des annonces</h2>

  <ul>
    {% for advert in listAdverts %}
      <li>
        <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
          {{ advert.title }}
        </a>
        par {{ advert.author }},
        le {{ advert.date|date('d/m/Y') }}
      </li>
    {% else %}
      <li>Pas (encore !) d'annonces</li>
    {% endfor %}
  </ul>

  <ul class="pagination">
    {# On utilise la fonction range(a, b) qui crée un tableau de valeurs entre a et b #}
    {% for p in range(1, nbPages) %}
      <li{% if p == page %} class="active"{% endif %}>
        <a href="{{ path('oc_platform_home', {'page': p}) }}">{{ p }}</a>
      </li>
    {% endfor %}
  </ul>
  
{% endblock %}

src/Cydream/PlatformBundle/Resources/views/Advert/menu.html.twig
{# Ce template n'hérite de personne, tout comme le template inclus avec {{ include() }}. #}

<ul class="nav nav-pills nav-stacked">
  {% for advert in listAdverts %}
    <li>
      <a href="{{ path('oc_platform_view', {'id': advert.id}) }}">
        {{ advert.title }}
      </a>
    </li>
  {% endfor %}
</ul>

src/Cydream/PlatformBundle/Resources/views/Advert/view.html.twig
{# src/Cydream/PlatformBundle/Resources/view/Advert/view.html.twig #}

{% extends "CydreamPlatformBundle::layout.html.twig" %}

{% block title %}
  Lecture d'une annonce - {{ parent() }}
{% endblock %}

{% block ocplatform_body %}

  <div style="float: left; margin-right: 1em;">
    {# On vérifie qu'une image soit bien associée à l'article #}
    {% if advert.image is not null %}
      <img
  src="{{ asset(advert.image.uploadDir ~ '/' ~ advert.image.url) }}"
  alt="{{ advert.image.alt }}"
/>
    {% endif %}
  </div>

  <h2>{{ advert.title }}</h2>
  <i>Par {{ advert.author }}, le {{ advert.date|date('d/m/Y') }}</i>

  <div class="well">
    {{ advert.content }}
  </div>

  {% if not advert.categories.empty %}
    <p>
      Cette annonce est parue dans les catégories suivantes :
      {% for category in advert.categories %}
        {{ category.name }}{% if not loop.last %}, {% endif %}
      {% endfor %}
    </p>
  {% endif %}

  {% if listAdvertSkills|length > 0 %}
    <div>
      Cette annonce requiert les compétences suivantes :
      <ul>
        {% for advertSkill in listAdvertSkills %}
          <li>{{ advertSkill.skill.name }} : niveau {{ advertSkill.level }}</li>
        {% endfor %}
      </ul>
    </div>
  {% endif %}

  <p>
    <a href="{{ path('oc_platform_home') }}" class="btn btn-default">
      <i class="glyphicon glyphicon-chevron-left"></i>
      Retour à la liste
    </a>
    <a href="{{ path('oc_platform_edit', {'id': advert.id}) }}" class="btn btn-default">
      <i class="glyphicon glyphicon-edit"></i>
      Modifier l'annonce
    </a>
    <a href="{{ path('oc_platform_delete', {'id': advert.id}) }}" class="btn btn-danger">
      <i class="glyphicon glyphicon-trash"></i>
      Supprimer l'annonce
    </a>
  </p>

{% endblock %}